# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleWeather_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'

  # Pods for AppleWeather_Clone

end
